### ISSUE TITLE
未能成功加载扩展程序,怎么解决？

### ISSUE THREAD

**Issue by Git-star-programmer** [zman2013/chrome-ext-huawei-mall#10]
未能成功加载扩展程序
文件
E:\desklop\chrome-ext-huawei-mall-main
错误
Error at key 'web_accessible_resources'. Parsing array failed at index 0: expected string, got dictionary
无法加载清单。

**Comment by zman2013** [comment]
修复了，请 pull 最新的代码。
manifest_version 没有更新导致的
