### ISSUE TITLE
具体是怎么操作的呀？

### ISSUE THREAD

**Issue by 2tunnel** [zman2013/chrome-ext-huawei-mall#3]
你好呀 作者
装好了插件 刚刚21点的时候 试了一下 好像没有效果。
插件会有一个小白框 是到时间就点击那个小白框吗？
谢谢作者

**Comment by BINFeng94** [comment]
自动工作，打开f12看看控制台

**Comment by zman2013** [comment]
@g9dl1ca 加了readme，可以参考下
