### ISSUE TITLE
if (safari_chrome && (nodeName != 'INPUT' || nodeName != 'BUTTON'))

### ISSUE THREAD

**Issue by wjiafengw** [zman2013/chrome-ext-huawei-mall#6]
if (safari_chrome && (nodeName != 'INPUT' || nodeName != 'BUTTON'))
这个判断后半部分是永真的吧？

**Comment by zman2013** [comment]
在chrome浏览器下你是对的，但是不清楚在safari使用该插件时是否会触发此条件，这个没有去验证了。
